services:
  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
